# Use an official Node runtime as a parent image
FROM node:18-alpine

# Set the working directory
WORKDIR /frontend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --frozen-lockfile

COPY public/ /frontend/public
COPY src/ /frontend/src

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
