services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 5000:5000
    env_file:
      - backend/.env
      - backend/.env.production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      target: production
    ports:
      - 443:443
    env_file:
      - frontend/.env.production
    depends_on:
      - backend