services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    env_file:
      - backend/.env
      - backend/.env.development
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - frontend/.env.development
    depends_on:
      - backend

  db:
    #container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5433:5433
    command: -p 5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./init_data/init_maintables_data.sql:/docker-entrypoint-initdb.d/init_data.sql
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d database -U postgres -h localhost -p 5433"]
      interval: 15s
      timeout: 15s
      retries: 10

volumes:
  db_data: