"""added created_at column in Tradeup model

Revision ID: 49d2d24c8e83
Revises: fb8b114ed7ea
Create Date: 2025-02-16 18:57:17.522700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d2d24c8e83'
down_revision = 'fb8b114ed7ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tradeup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tradeup', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
