"""added Token table

Revision ID: 67ba1d52c064
Revises: 55c4473bd7cb
Create Date: 2025-02-11 19:12:37.688534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ba1d52c064'
down_revision = '55c4473bd7cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skin_conditions', schema=None) as batch_op:
        batch_op.alter_column('stattrak',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('skins', schema=None) as batch_op:
        batch_op.alter_column('stattrak_available',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skins', schema=None) as batch_op:
        batch_op.alter_column('stattrak_available',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('skin_conditions', schema=None) as batch_op:
        batch_op.alter_column('stattrak',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
