"""changed column name from 'float' to 'skin_float' in tradeup entry tables to prevent type confusion

Revision ID: 8cf3b5dc6a51
Revises: d082eab574cd
Create Date: 2024-08-05 00:27:17.792940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf3b5dc6a51'
down_revision = 'd082eab574cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('input_tradeup_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skin_float', sa.Float(), nullable=False))
        batch_op.drop_column('float')

    with op.batch_alter_table('output_tradeup_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skin_float', sa.Float(), nullable=False))
        batch_op.drop_column('float')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('output_tradeup_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('float', sa.FLOAT(), nullable=False))
        batch_op.drop_column('skin_float')

    with op.batch_alter_table('input_tradeup_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('float', sa.FLOAT(), nullable=False))
        batch_op.drop_column('skin_float')

    # ### end Alembic commands ###
