"""Added released_date column to Tradeup model

Revision ID: 97e5732f253f
Revises: 49d2d24c8e83
Create Date: 2025-02-17 21:45:07.519500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e5732f253f'
down_revision = '49d2d24c8e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tradeup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tradeup', schema=None) as batch_op:
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###
