"""added last_of_rarity column in Skins table to identify the skins whose rarity is the last of its collection

Revision ID: f246a1b1fa87
Revises: eb0e7d09e30f
Create Date: 2025-02-12 14:57:16.800287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f246a1b1fa87'
down_revision = 'eb0e7d09e30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_of_rarity', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skins', schema=None) as batch_op:
        batch_op.drop_column('last_of_rarity')

    # ### end Alembic commands ###
