"""added tradeup types. added relations between purchasable tradeups and users, and between private tradeups and users.

Revision ID: fae9fcf4e0a4
Revises: 4d8b3cd4c785
Create Date: 2024-08-03 01:02:18.418708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae9fcf4e0a4'
down_revision = '4d8b3cd4c785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tradeup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tradeup_type', sa.Enum('PUBLIC', 'PURCHASABLE', 'PRIVATE', name='tradeuptype'), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tradeup', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('tradeup_type')

    # ### end Alembic commands ###
