"""Changed primary key column in User from id to steam_id. Added columns avatar_url, personaname and signup_date.

Revision ID: fb8b114ed7ea
Revises: f246a1b1fa87
Create Date: 2025-02-14 18:32:20.784232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8b114ed7ea'
down_revision = 'f246a1b1fa87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_collections')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_collections_name'), ['name'])

    with op.batch_alter_table('private_tradeup_user', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_private_tradeup_user_user_id_user'), 'user', ['user_id'], ['steam_id'])

    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tokens_user_id_user'), 'user', ['user_id'], ['steam_id'])

    with op.batch_alter_table('tradeup_purchase', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tradeup_purchase_user_id_user'), 'user', ['user_id'], ['steam_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steam_id', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('personaname', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('signup_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.drop_index('ix_user_email')
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.drop_column('id')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.create_index('ix_user_email', ['email'], unique=1)
        batch_op.drop_column('signup_date')
        batch_op.drop_column('personaname')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('steam_id')

    with op.batch_alter_table('tradeup_purchase', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tradeup_purchase_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tokens_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('private_tradeup_user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_private_tradeup_user_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_collections_name'), type_='unique')

    op.create_table('_alembic_tmp_collections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_collections_name')
    )
    # ### end Alembic commands ###
